/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "filament.exports.download": [
        {
            "name": "export",
            "required": true,
            "binding": "id"
        }
    ],
    "filament.imports.failed-rows.download": [
        {
            "name": "import",
            "required": true,
            "binding": "id"
        }
    ],
    "filament.admin.auth.logout": [],
    "filament.admin.pages.dashboard": [],
    "filament.admin.resources.audits.index": [],
    "filament.admin.resources.audits.create": [],
    "filament.admin.resources.audits.view": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.clients.index": [],
    "filament.admin.resources.clients.create": [],
    "filament.admin.resources.clients.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.failed-jobs.index": [],
    "filament.admin.resources.failed-jobs.view": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.organization-invitations.index": [],
    "filament.admin.resources.organization-invitations.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.organization-invitations.view": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.organizations.index": [],
    "filament.admin.resources.organizations.create": [],
    "filament.admin.resources.organizations.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.organizations.view": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.project-members.index": [],
    "filament.admin.resources.project-members.create": [],
    "filament.admin.resources.project-members.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.project-members.view": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.projects.index": [],
    "filament.admin.resources.projects.create": [],
    "filament.admin.resources.projects.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.reports.index": [],
    "filament.admin.resources.reports.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.reports.view": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.tags.index": [],
    "filament.admin.resources.tags.create": [],
    "filament.admin.resources.tags.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.tasks.index": [],
    "filament.admin.resources.tasks.create": [],
    "filament.admin.resources.tasks.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.time-entries.index": [],
    "filament.admin.resources.time-entries.create": [],
    "filament.admin.resources.time-entries.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.tokens.index": [],
    "filament.admin.resources.tokens.view": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.users.index": [],
    "filament.admin.resources.users.create": [],
    "filament.admin.resources.users.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.users.view": [
        {
            "name": "record",
            "required": true
        }
    ],
    "passport.token": [],
    "passport.authorizations.authorize": [],
    "passport.device": [],
    "passport.device.code": [],
    "passport.token.refresh": [],
    "passport.authorizations.approve": [],
    "passport.authorizations.deny": [],
    "passport.device.authorizations.authorize": [],
    "passport.device.authorizations.approve": [],
    "passport.device.authorizations.deny": [],
    "default.livewire.update": [],
    "livewire.upload-file": [],
    "livewire.preview-file": [
        {
            "name": "filename",
            "required": true
        }
    ],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "filament-impersonate.leave": [],
    "api.v1.organizations.show": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.organizations.update": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.organizations.destroy": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.members.index": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.members.update": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        },
        {
            "name": "member",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.members.destroy": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        },
        {
            "name": "member",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.members.invite-placeholder": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        },
        {
            "name": "member",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.members.make-placeholder": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        },
        {
            "name": "member",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.members.merge-into": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        },
        {
            "name": "member",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.users.me": [],
    "api.v1.users.update-current-organization": [],
    "api.v1.users.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.users.resend-email-verification": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.users.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.users.reset-pending-email": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.api-tokens.index": [],
    "api.v1.api-tokens.store": [],
    "api.v1.api-tokens.revoke": [
        {
            "name": "apiToken",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.api-tokens.destroy": [
        {
            "name": "apiToken",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.users.memberships.my-memberships": [],
    "api.v1.invitations.index": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.invitations.store": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.invitations.resend": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        },
        {
            "name": "invitation",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.invitations.destroy": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        },
        {
            "name": "invitation",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.projects.index": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.projects.show": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        },
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.projects.store": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.projects.update": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        },
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.projects.destroy": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        },
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.project-members.index": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        },
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.project-members.store": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        },
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.project-members.update": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        },
        {
            "name": "projectMember",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.project-members.destroy": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        },
        {
            "name": "projectMember",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.time-entries.index": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.time-entries.index-export": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.time-entries.aggregate": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.time-entries.aggregate-export": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.time-entries.store": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.time-entries.update": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        },
        {
            "name": "timeEntry",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.time-entries.update-multiple": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.time-entries.destroy": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        },
        {
            "name": "timeEntry",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.time-entries.destroy-multiple": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.users.time-entries.my-active": [],
    "api.v1.users.time-entries.my": [],
    "api.v1.reports.index": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.reports.show": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        },
        {
            "name": "report",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.reports.store": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.reports.update": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        },
        {
            "name": "report",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.reports.destroy": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        },
        {
            "name": "report",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.charts.weekly-project-overview": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.charts.latest-tasks": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.charts.last-seven-days": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.charts.latest-team-activity": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.charts.daily-tracked-hours": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.charts.total-weekly-time": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.charts.total-weekly-billable-time": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.charts.total-weekly-billable-amount": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.charts.weekly-history": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.tags.index": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.tags.store": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.tags.update": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        },
        {
            "name": "tag",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.tags.destroy": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        },
        {
            "name": "tag",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.clients.index": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.clients.store": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.clients.update": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        },
        {
            "name": "client",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.clients.destroy": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        },
        {
            "name": "client",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.tasks.index": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.tasks.store": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.tasks.update": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        },
        {
            "name": "task",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.tasks.destroy": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        },
        {
            "name": "task",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.import.index": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.import.import": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.export.export": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "api.v1.currencies.index": [],
    "api.v1.time-zones.index": [],
    "api.v1.public.reports.show": [],
    "api.": [],
    "login": [],
    "logout": [],
    "auth.google.redirect": [],
    "auth.google.callback": [],
    "shared-report": [],
    "dashboard": [],
    "time": [],
    "calendar": [],
    "timesheet": [],
    "reporting": [],
    "reporting.detailed": [],
    "reporting.shared": [],
    "projects": [],
    "projects.show": [
        {
            "name": "project",
            "required": true
        }
    ],
    "clients": [],
    "members": [],
    "tags": [],
    "import": [],
    "organizations.show": [
        {
            "name": "organizationId",
            "required": true
        }
    ],
    "profile.show": [],
    "other-browser-sessions.destroy": [],
    "team-invitations.accept": [
        {
            "name": "invitation",
            "required": true,
            "binding": "id"
        }
    ],
    "organization-invitations.accept": [
        {
            "name": "invitation",
            "required": true,
            "binding": "id"
        }
    ],
    "users.verify-email-change": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "telescope": [
        {
            "name": "view",
            "required": false
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ],
    "scramble.docs.ui": [],
    "scramble.docs.document": []
}
}
export {};
