const Ziggy = {
    'url': 'http://localhost:8000',
    'port': 8000,
    'defaults': {},
    'routes': {
        'filament.exports.download': {
            'uri': 'filament/exports/{export}/download',
            'methods': ['GET', 'HEAD'],
            'parameters': ['export'],
            'bindings': { 'export': 'id' },
        },
        'filament.imports.failed-rows.download': {
            'uri': 'filament/imports/{import}/failed-rows/download',
            'methods': ['GET', 'HEAD'],
            'parameters': ['import'],
            'bindings': { 'import': 'id' },
        },
        'filament.admin.auth.logout': { 'uri': 'admin/logout', 'methods': ['POST'] },
        'filament.admin.pages.dashboard': { 'uri': 'admin', 'methods': ['GET', 'HEAD'] },
        'filament.admin.resources.audits.index': {
            'uri': 'admin/audits',
            'methods': ['GET', 'HEAD'],
        },
        'filament.admin.resources.audits.create': {
            'uri': 'admin/audits/create',
            'methods': ['GET', 'HEAD'],
        },
        'filament.admin.resources.audits.view': {
            'uri': 'admin/audits/{record}',
            'methods': ['GET', 'HEAD'],
            'parameters': ['record'],
        },
        'filament.admin.resources.clients.index': {
            'uri': 'admin/clients',
            'methods': ['GET', 'HEAD'],
        },
        'filament.admin.resources.clients.create': {
            'uri': 'admin/clients/create',
            'methods': ['GET', 'HEAD'],
        },
        'filament.admin.resources.clients.edit': {
            'uri': 'admin/clients/{record}/edit',
            'methods': ['GET', 'HEAD'],
            'parameters': ['record'],
        },
        'filament.admin.resources.failed-jobs.index': {
            'uri': 'admin/failed-jobs',
            'methods': ['GET', 'HEAD'],
        },
        'filament.admin.resources.failed-jobs.view': {
            'uri': 'admin/failed-jobs/{record}',
            'methods': ['GET', 'HEAD'],
            'parameters': ['record'],
        },
        'filament.admin.resources.organization-invitations.index': {
            'uri': 'admin/organization-invitations',
            'methods': ['GET', 'HEAD'],
        },
        'filament.admin.resources.organization-invitations.edit': {
            'uri': 'admin/organization-invitations/{record}/edit',
            'methods': ['GET', 'HEAD'],
            'parameters': ['record'],
        },
        'filament.admin.resources.organization-invitations.view': {
            'uri': 'admin/organization-invitations/{record}',
            'methods': ['GET', 'HEAD'],
            'parameters': ['record'],
        },
        'filament.admin.resources.organizations.index': {
            'uri': 'admin/organizations',
            'methods': ['GET', 'HEAD'],
        },
        'filament.admin.resources.organizations.create': {
            'uri': 'admin/organizations/create',
            'methods': ['GET', 'HEAD'],
        },
        'filament.admin.resources.organizations.edit': {
            'uri': 'admin/organizations/{record}/edit',
            'methods': ['GET', 'HEAD'],
            'parameters': ['record'],
        },
        'filament.admin.resources.organizations.view': {
            'uri': 'admin/organizations/{record}',
            'methods': ['GET', 'HEAD'],
            'parameters': ['record'],
        },
        'filament.admin.resources.project-members.index': {
            'uri': 'admin/project-members',
            'methods': ['GET', 'HEAD'],
        },
        'filament.admin.resources.project-members.create': {
            'uri': 'admin/project-members/create',
            'methods': ['GET', 'HEAD'],
        },
        'filament.admin.resources.project-members.edit': {
            'uri': 'admin/project-members/{record}/edit',
            'methods': ['GET', 'HEAD'],
            'parameters': ['record'],
        },
        'filament.admin.resources.project-members.view': {
            'uri': 'admin/project-members/{record}',
            'methods': ['GET', 'HEAD'],
            'parameters': ['record'],
        },
        'filament.admin.resources.projects.index': {
            'uri': 'admin/projects',
            'methods': ['GET', 'HEAD'],
        },
        'filament.admin.resources.projects.create': {
            'uri': 'admin/projects/create',
            'methods': ['GET', 'HEAD'],
        },
        'filament.admin.resources.projects.edit': {
            'uri': 'admin/projects/{record}/edit',
            'methods': ['GET', 'HEAD'],
            'parameters': ['record'],
        },
        'filament.admin.resources.reports.index': {
            'uri': 'admin/reports',
            'methods': ['GET', 'HEAD'],
        },
        'filament.admin.resources.reports.edit': {
            'uri': 'admin/reports/{record}/edit',
            'methods': ['GET', 'HEAD'],
            'parameters': ['record'],
        },
        'filament.admin.resources.reports.view': {
            'uri': 'admin/reports/{record}',
            'methods': ['GET', 'HEAD'],
            'parameters': ['record'],
        },
        'filament.admin.resources.tags.index': { 'uri': 'admin/tags', 'methods': ['GET', 'HEAD'] },
        'filament.admin.resources.tags.create': {
            'uri': 'admin/tags/create',
            'methods': ['GET', 'HEAD'],
        },
        'filament.admin.resources.tags.edit': {
            'uri': 'admin/tags/{record}/edit',
            'methods': ['GET', 'HEAD'],
            'parameters': ['record'],
        },
        'filament.admin.resources.tasks.index': {
            'uri': 'admin/tasks',
            'methods': ['GET', 'HEAD'],
        },
        'filament.admin.resources.tasks.create': {
            'uri': 'admin/tasks/create',
            'methods': ['GET', 'HEAD'],
        },
        'filament.admin.resources.tasks.edit': {
            'uri': 'admin/tasks/{record}/edit',
            'methods': ['GET', 'HEAD'],
            'parameters': ['record'],
        },
        'filament.admin.resources.time-entries.index': {
            'uri': 'admin/time-entries',
            'methods': ['GET', 'HEAD'],
        },
        'filament.admin.resources.time-entries.create': {
            'uri': 'admin/time-entries/create',
            'methods': ['GET', 'HEAD'],
        },
        'filament.admin.resources.time-entries.edit': {
            'uri': 'admin/time-entries/{record}/edit',
            'methods': ['GET', 'HEAD'],
            'parameters': ['record'],
        },
        'filament.admin.resources.tokens.index': {
            'uri': 'admin/tokens',
            'methods': ['GET', 'HEAD'],
        },
        'filament.admin.resources.tokens.view': {
            'uri': 'admin/tokens/{record}',
            'methods': ['GET', 'HEAD'],
            'parameters': ['record'],
        },
        'filament.admin.resources.users.index': {
            'uri': 'admin/users',
            'methods': ['GET', 'HEAD'],
        },
        'filament.admin.resources.users.create': {
            'uri': 'admin/users/create',
            'methods': ['GET', 'HEAD'],
        },
        'filament.admin.resources.users.edit': {
            'uri': 'admin/users/{record}/edit',
            'methods': ['GET', 'HEAD'],
            'parameters': ['record'],
        },
        'filament.admin.resources.users.view': {
            'uri': 'admin/users/{record}',
            'methods': ['GET', 'HEAD'],
            'parameters': ['record'],
        },
        'passport.token': { 'uri': 'oauth/token', 'methods': ['POST'] },
        'passport.authorizations.authorize': {
            'uri': 'oauth/authorize',
            'methods': ['GET', 'HEAD'],
        },
        'passport.device': { 'uri': 'oauth/device', 'methods': ['GET', 'HEAD'] },
        'passport.device.code': { 'uri': 'oauth/device/code', 'methods': ['POST'] },
        'passport.token.refresh': { 'uri': 'oauth/token/refresh', 'methods': ['POST'] },
        'passport.authorizations.approve': { 'uri': 'oauth/authorize', 'methods': ['POST'] },
        'passport.authorizations.deny': { 'uri': 'oauth/authorize', 'methods': ['DELETE'] },
        'passport.device.authorizations.authorize': {
            'uri': 'oauth/device/authorize',
            'methods': ['GET', 'HEAD'],
        },
        'passport.device.authorizations.approve': {
            'uri': 'oauth/device/authorize',
            'methods': ['POST'],
        },
        'passport.device.authorizations.deny': {
            'uri': 'oauth/device/authorize',
            'methods': ['DELETE'],
        },
        'default.livewire.update': { 'uri': 'livewire/update', 'methods': ['POST'] },
        'livewire.upload-file': { 'uri': 'livewire/upload-file', 'methods': ['POST'] },
        'livewire.preview-file': {
            'uri': 'livewire/preview-file/{filename}',
            'methods': ['GET', 'HEAD'],
            'parameters': ['filename'],
        },
        'ignition.healthCheck': { 'uri': '_ignition/health-check', 'methods': ['GET', 'HEAD'] },
        'ignition.executeSolution': { 'uri': '_ignition/execute-solution', 'methods': ['POST'] },
        'ignition.updateConfig': { 'uri': '_ignition/update-config', 'methods': ['POST'] },
        'filament-impersonate.leave': {
            'uri': 'filament-impersonate/leave',
            'methods': ['GET', 'HEAD'],
        },
        'api.v1.organizations.show': {
            'uri': 'api/v1/organizations/{organization}',
            'methods': ['GET', 'HEAD'],
            'parameters': ['organization'],
            'bindings': { 'organization': 'id' },
        },
        'api.v1.organizations.update': {
            'uri': 'api/v1/organizations/{organization}',
            'methods': ['PUT'],
            'parameters': ['organization'],
            'bindings': { 'organization': 'id' },
        },
        'api.v1.organizations.destroy': {
            'uri': 'api/v1/organizations/{organization}',
            'methods': ['DELETE'],
            'parameters': ['organization'],
            'bindings': { 'organization': 'id' },
        },
        'api.v1.members.index': {
            'uri': 'api/v1/organizations/{organization}/members',
            'methods': ['GET', 'HEAD'],
            'parameters': ['organization'],
            'bindings': { 'organization': 'id' },
        },
        'api.v1.members.update': {
            'uri': 'api/v1/organizations/{organization}/members/{member}',
            'methods': ['PUT'],
            'parameters': ['organization', 'member'],
            'bindings': { 'organization': 'id', 'member': 'id' },
        },
        'api.v1.members.destroy': {
            'uri': 'api/v1/organizations/{organization}/members/{member}',
            'methods': ['DELETE'],
            'parameters': ['organization', 'member'],
            'bindings': { 'organization': 'id', 'member': 'id' },
        },
        'api.v1.members.invite-placeholder': {
            'uri': 'api/v1/organizations/{organization}/members/{member}/invite-placeholder',
            'methods': ['POST'],
            'parameters': ['organization', 'member'],
            'bindings': { 'organization': 'id', 'member': 'id' },
        },
        'api.v1.members.make-placeholder': {
            'uri': 'api/v1/organizations/{organization}/members/{member}/make-placeholder',
            'methods': ['POST'],
            'parameters': ['organization', 'member'],
            'bindings': { 'organization': 'id', 'member': 'id' },
        },
        'api.v1.members.merge-into': {
            'uri': 'api/v1/organizations/{organization}/member/{member}/merge-into',
            'methods': ['POST'],
            'parameters': ['organization', 'member'],
            'bindings': { 'organization': 'id', 'member': 'id' },
        },
        'api.v1.users.me': { 'uri': 'api/v1/users/me', 'methods': ['GET', 'HEAD'] },
        'api.v1.users.update-current-organization': {
            'uri': 'api/v1/users/me/current-organization',
            'methods': ['PUT'],
        },
        'api.v1.users.update': {
            'uri': 'api/v1/users/{user}',
            'methods': ['PUT'],
            'parameters': ['user'],
            'bindings': { 'user': 'id' },
        },
        'api.v1.users.resend-email-verification': {
            'uri': 'api/v1/users/{user}/resend-email-verification',
            'methods': ['POST'],
            'parameters': ['user'],
            'bindings': { 'user': 'id' },
        },
        'api.v1.users.destroy': {
            'uri': 'api/v1/users/{user}',
            'methods': ['DELETE'],
            'parameters': ['user'],
            'bindings': { 'user': 'id' },
        },
        'api.v1.users.reset-pending-email': {
            'uri': 'api/v1/users/{user}/reset-pending-email',
            'methods': ['POST'],
            'parameters': ['user'],
            'bindings': { 'user': 'id' },
        },
        'api.v1.api-tokens.index': {
            'uri': 'api/v1/users/me/api-tokens',
            'methods': ['GET', 'HEAD'],
        },
        'api.v1.api-tokens.store': { 'uri': 'api/v1/users/me/api-tokens', 'methods': ['POST'] },
        'api.v1.api-tokens.revoke': {
            'uri': 'api/v1/users/me/api-tokens/{apiToken}/revoke',
            'methods': ['POST'],
            'parameters': ['apiToken'],
            'bindings': { 'apiToken': 'id' },
        },
        'api.v1.api-tokens.destroy': {
            'uri': 'api/v1/users/me/api-tokens/{apiToken}',
            'methods': ['DELETE'],
            'parameters': ['apiToken'],
            'bindings': { 'apiToken': 'id' },
        },
        'api.v1.users.memberships.my-memberships': {
            'uri': 'api/v1/users/me/memberships',
            'methods': ['GET', 'HEAD'],
        },
        'api.v1.invitations.index': {
            'uri': 'api/v1/organizations/{organization}/invitations',
            'methods': ['GET', 'HEAD'],
            'parameters': ['organization'],
            'bindings': { 'organization': 'id' },
        },
        'api.v1.invitations.store': {
            'uri': 'api/v1/organizations/{organization}/invitations',
            'methods': ['POST'],
            'parameters': ['organization'],
            'bindings': { 'organization': 'id' },
        },
        'api.v1.invitations.resend': {
            'uri': 'api/v1/organizations/{organization}/invitations/{invitation}/resend',
            'methods': ['POST'],
            'parameters': ['organization', 'invitation'],
            'bindings': { 'organization': 'id', 'invitation': 'id' },
        },
        'api.v1.invitations.destroy': {
            'uri': 'api/v1/organizations/{organization}/invitations/{invitation}',
            'methods': ['DELETE'],
            'parameters': ['organization', 'invitation'],
            'bindings': { 'organization': 'id', 'invitation': 'id' },
        },
        'api.v1.projects.index': {
            'uri': 'api/v1/organizations/{organization}/projects',
            'methods': ['GET', 'HEAD'],
            'parameters': ['organization'],
            'bindings': { 'organization': 'id' },
        },
        'api.v1.projects.show': {
            'uri': 'api/v1/organizations/{organization}/projects/{project}',
            'methods': ['GET', 'HEAD'],
            'parameters': ['organization', 'project'],
            'bindings': { 'organization': 'id', 'project': 'id' },
        },
        'api.v1.projects.store': {
            'uri': 'api/v1/organizations/{organization}/projects',
            'methods': ['POST'],
            'parameters': ['organization'],
            'bindings': { 'organization': 'id' },
        },
        'api.v1.projects.update': {
            'uri': 'api/v1/organizations/{organization}/projects/{project}',
            'methods': ['PUT'],
            'parameters': ['organization', 'project'],
            'bindings': { 'organization': 'id', 'project': 'id' },
        },
        'api.v1.projects.destroy': {
            'uri': 'api/v1/organizations/{organization}/projects/{project}',
            'methods': ['DELETE'],
            'parameters': ['organization', 'project'],
            'bindings': { 'organization': 'id', 'project': 'id' },
        },
        'api.v1.project-members.index': {
            'uri': 'api/v1/organizations/{organization}/projects/{project}/project-members',
            'methods': ['GET', 'HEAD'],
            'parameters': ['organization', 'project'],
            'bindings': { 'organization': 'id', 'project': 'id' },
        },
        'api.v1.project-members.store': {
            'uri': 'api/v1/organizations/{organization}/projects/{project}/project-members',
            'methods': ['POST'],
            'parameters': ['organization', 'project'],
            'bindings': { 'organization': 'id', 'project': 'id' },
        },
        'api.v1.project-members.update': {
            'uri': 'api/v1/organizations/{organization}/project-members/{projectMember}',
            'methods': ['PUT'],
            'parameters': ['organization', 'projectMember'],
            'bindings': { 'organization': 'id', 'projectMember': 'id' },
        },
        'api.v1.project-members.destroy': {
            'uri': 'api/v1/organizations/{organization}/project-members/{projectMember}',
            'methods': ['DELETE'],
            'parameters': ['organization', 'projectMember'],
            'bindings': { 'organization': 'id', 'projectMember': 'id' },
        },
        'api.v1.time-entries.index': {
            'uri': 'api/v1/organizations/{organization}/time-entries',
            'methods': ['GET', 'HEAD'],
            'parameters': ['organization'],
            'bindings': { 'organization': 'id' },
        },
        'api.v1.time-entries.index-export': {
            'uri': 'api/v1/organizations/{organization}/time-entries/export',
            'methods': ['GET', 'HEAD'],
            'parameters': ['organization'],
            'bindings': { 'organization': 'id' },
        },
        'api.v1.time-entries.aggregate': {
            'uri': 'api/v1/organizations/{organization}/time-entries/aggregate',
            'methods': ['GET', 'HEAD'],
            'parameters': ['organization'],
            'bindings': { 'organization': 'id' },
        },
        'api.v1.time-entries.aggregate-export': {
            'uri': 'api/v1/organizations/{organization}/time-entries/aggregate/export',
            'methods': ['GET', 'HEAD'],
            'parameters': ['organization'],
            'bindings': { 'organization': 'id' },
        },
        'api.v1.time-entries.store': {
            'uri': 'api/v1/organizations/{organization}/time-entries',
            'methods': ['POST'],
            'parameters': ['organization'],
            'bindings': { 'organization': 'id' },
        },
        'api.v1.time-entries.update': {
            'uri': 'api/v1/organizations/{organization}/time-entries/{timeEntry}',
            'methods': ['PUT'],
            'parameters': ['organization', 'timeEntry'],
            'bindings': { 'organization': 'id', 'timeEntry': 'id' },
        },
        'api.v1.time-entries.update-multiple': {
            'uri': 'api/v1/organizations/{organization}/time-entries',
            'methods': ['PATCH'],
            'parameters': ['organization'],
            'bindings': { 'organization': 'id' },
        },
        'api.v1.time-entries.destroy': {
            'uri': 'api/v1/organizations/{organization}/time-entries/{timeEntry}',
            'methods': ['DELETE'],
            'parameters': ['organization', 'timeEntry'],
            'bindings': { 'organization': 'id', 'timeEntry': 'id' },
        },
        'api.v1.time-entries.destroy-multiple': {
            'uri': 'api/v1/organizations/{organization}/time-entries',
            'methods': ['DELETE'],
            'parameters': ['organization'],
            'bindings': { 'organization': 'id' },
        },
        'api.v1.users.time-entries.my-active': {
            'uri': 'api/v1/users/me/time-entries/active',
            'methods': ['GET', 'HEAD'],
        },
        'api.v1.users.time-entries.my': {
            'uri': 'api/v1/users/me/time-entries',
            'methods': ['GET', 'HEAD'],
        },
        'api.v1.reports.index': {
            'uri': 'api/v1/organizations/{organization}/reports',
            'methods': ['GET', 'HEAD'],
            'parameters': ['organization'],
            'bindings': { 'organization': 'id' },
        },
        'api.v1.reports.show': {
            'uri': 'api/v1/organizations/{organization}/reports/{report}',
            'methods': ['GET', 'HEAD'],
            'parameters': ['organization', 'report'],
            'bindings': { 'organization': 'id', 'report': 'id' },
        },
        'api.v1.reports.store': {
            'uri': 'api/v1/organizations/{organization}/reports',
            'methods': ['POST'],
            'parameters': ['organization'],
            'bindings': { 'organization': 'id' },
        },
        'api.v1.reports.update': {
            'uri': 'api/v1/organizations/{organization}/reports/{report}',
            'methods': ['PUT'],
            'parameters': ['organization', 'report'],
            'bindings': { 'organization': 'id', 'report': 'id' },
        },
        'api.v1.reports.destroy': {
            'uri': 'api/v1/organizations/{organization}/reports/{report}',
            'methods': ['DELETE'],
            'parameters': ['organization', 'report'],
            'bindings': { 'organization': 'id', 'report': 'id' },
        },
        'api.v1.charts.weekly-project-overview': {
            'uri': 'api/v1/organizations/{organization}/charts/weekly-project-overview',
            'methods': ['GET', 'HEAD'],
            'parameters': ['organization'],
            'bindings': { 'organization': 'id' },
        },
        'api.v1.charts.latest-tasks': {
            'uri': 'api/v1/organizations/{organization}/charts/latest-tasks',
            'methods': ['GET', 'HEAD'],
            'parameters': ['organization'],
            'bindings': { 'organization': 'id' },
        },
        'api.v1.charts.last-seven-days': {
            'uri': 'api/v1/organizations/{organization}/charts/last-seven-days',
            'methods': ['GET', 'HEAD'],
            'parameters': ['organization'],
            'bindings': { 'organization': 'id' },
        },
        'api.v1.charts.latest-team-activity': {
            'uri': 'api/v1/organizations/{organization}/charts/latest-team-activity',
            'methods': ['GET', 'HEAD'],
            'parameters': ['organization'],
            'bindings': { 'organization': 'id' },
        },
        'api.v1.charts.daily-tracked-hours': {
            'uri': 'api/v1/organizations/{organization}/charts/daily-tracked-hours',
            'methods': ['GET', 'HEAD'],
            'parameters': ['organization'],
            'bindings': { 'organization': 'id' },
        },
        'api.v1.charts.total-weekly-time': {
            'uri': 'api/v1/organizations/{organization}/charts/total-weekly-time',
            'methods': ['GET', 'HEAD'],
            'parameters': ['organization'],
            'bindings': { 'organization': 'id' },
        },
        'api.v1.charts.total-weekly-billable-time': {
            'uri': 'api/v1/organizations/{organization}/charts/total-weekly-billable-time',
            'methods': ['GET', 'HEAD'],
            'parameters': ['organization'],
            'bindings': { 'organization': 'id' },
        },
        'api.v1.charts.total-weekly-billable-amount': {
            'uri': 'api/v1/organizations/{organization}/charts/total-weekly-billable-amount',
            'methods': ['GET', 'HEAD'],
            'parameters': ['organization'],
            'bindings': { 'organization': 'id' },
        },
        'api.v1.charts.weekly-history': {
            'uri': 'api/v1/organizations/{organization}/charts/weekly-history',
            'methods': ['GET', 'HEAD'],
            'parameters': ['organization'],
            'bindings': { 'organization': 'id' },
        },
        'api.v1.tags.index': {
            'uri': 'api/v1/organizations/{organization}/tags',
            'methods': ['GET', 'HEAD'],
            'parameters': ['organization'],
            'bindings': { 'organization': 'id' },
        },
        'api.v1.tags.store': {
            'uri': 'api/v1/organizations/{organization}/tags',
            'methods': ['POST'],
            'parameters': ['organization'],
            'bindings': { 'organization': 'id' },
        },
        'api.v1.tags.update': {
            'uri': 'api/v1/organizations/{organization}/tags/{tag}',
            'methods': ['PUT'],
            'parameters': ['organization', 'tag'],
            'bindings': { 'organization': 'id', 'tag': 'id' },
        },
        'api.v1.tags.destroy': {
            'uri': 'api/v1/organizations/{organization}/tags/{tag}',
            'methods': ['DELETE'],
            'parameters': ['organization', 'tag'],
            'bindings': { 'organization': 'id', 'tag': 'id' },
        },
        'api.v1.clients.index': {
            'uri': 'api/v1/organizations/{organization}/clients',
            'methods': ['GET', 'HEAD'],
            'parameters': ['organization'],
            'bindings': { 'organization': 'id' },
        },
        'api.v1.clients.store': {
            'uri': 'api/v1/organizations/{organization}/clients',
            'methods': ['POST'],
            'parameters': ['organization'],
            'bindings': { 'organization': 'id' },
        },
        'api.v1.clients.update': {
            'uri': 'api/v1/organizations/{organization}/clients/{client}',
            'methods': ['PUT'],
            'parameters': ['organization', 'client'],
            'bindings': { 'organization': 'id', 'client': 'id' },
        },
        'api.v1.clients.destroy': {
            'uri': 'api/v1/organizations/{organization}/clients/{client}',
            'methods': ['DELETE'],
            'parameters': ['organization', 'client'],
            'bindings': { 'organization': 'id', 'client': 'id' },
        },
        'api.v1.tasks.index': {
            'uri': 'api/v1/organizations/{organization}/tasks',
            'methods': ['GET', 'HEAD'],
            'parameters': ['organization'],
            'bindings': { 'organization': 'id' },
        },
        'api.v1.tasks.store': {
            'uri': 'api/v1/organizations/{organization}/tasks',
            'methods': ['POST'],
            'parameters': ['organization'],
            'bindings': { 'organization': 'id' },
        },
        'api.v1.tasks.update': {
            'uri': 'api/v1/organizations/{organization}/tasks/{task}',
            'methods': ['PUT'],
            'parameters': ['organization', 'task'],
            'bindings': { 'organization': 'id', 'task': 'id' },
        },
        'api.v1.tasks.destroy': {
            'uri': 'api/v1/organizations/{organization}/tasks/{task}',
            'methods': ['DELETE'],
            'parameters': ['organization', 'task'],
            'bindings': { 'organization': 'id', 'task': 'id' },
        },
        'api.v1.import.index': {
            'uri': 'api/v1/organizations/{organization}/importers',
            'methods': ['GET', 'HEAD'],
            'parameters': ['organization'],
            'bindings': { 'organization': 'id' },
        },
        'api.v1.import.import': {
            'uri': 'api/v1/organizations/{organization}/import',
            'methods': ['POST'],
            'parameters': ['organization'],
            'bindings': { 'organization': 'id' },
        },
        'api.v1.export.export': {
            'uri': 'api/v1/organizations/{organization}/export',
            'methods': ['POST'],
            'parameters': ['organization'],
            'bindings': { 'organization': 'id' },
        },
        'api.v1.currencies.index': { 'uri': 'api/v1/currencies', 'methods': ['GET', 'HEAD'] },
        'api.v1.time-zones.index': { 'uri': 'api/v1/time-zones', 'methods': ['GET', 'HEAD'] },
        'api.v1.public.reports.show': {
            'uri': 'api/v1/public/reports',
            'methods': ['GET', 'HEAD'],
        },
        'api.': { 'uri': 'api', 'methods': ['GET', 'HEAD'] },
        'login': { 'uri': 'login', 'methods': ['GET', 'HEAD'] },
        'logout': { 'uri': 'logout', 'methods': ['POST'] },
        'auth.google.redirect': { 'uri': 'auth/google', 'methods': ['GET', 'HEAD'] },
        'auth.google.callback': { 'uri': 'auth/google/callback', 'methods': ['GET', 'HEAD'] },
        'shared-report': { 'uri': 'shared-report', 'methods': ['GET', 'HEAD'] },
        'dashboard': { 'uri': 'dashboard', 'methods': ['GET', 'HEAD'] },
        'time': { 'uri': 'time', 'methods': ['GET', 'HEAD'] },
        'calendar': { 'uri': 'calendar', 'methods': ['GET', 'HEAD'] },
        'timesheet': { 'uri': 'timesheet', 'methods': ['GET', 'HEAD'] },
        'reporting': { 'uri': 'reporting', 'methods': ['GET', 'HEAD'] },
        'reporting.detailed': { 'uri': 'reporting/detailed', 'methods': ['GET', 'HEAD'] },
        'reporting.shared': { 'uri': 'reporting/shared', 'methods': ['GET', 'HEAD'] },
        'projects': { 'uri': 'projects', 'methods': ['GET', 'HEAD'] },
        'projects.show': {
            'uri': 'projects/{project}',
            'methods': ['GET', 'HEAD'],
            'parameters': ['project'],
        },
        'clients': { 'uri': 'clients', 'methods': ['GET', 'HEAD'] },
        'members': { 'uri': 'members', 'methods': ['GET', 'HEAD'] },
        'tags': { 'uri': 'tags', 'methods': ['GET', 'HEAD'] },
        'import': { 'uri': 'import', 'methods': ['GET', 'HEAD'] },
        'organizations.show': {
            'uri': 'organizations/{organizationId}',
            'methods': ['GET', 'HEAD'],
            'wheres': {
                'organizationId':
                    '[\\da-fA-F]{8}-[\\da-fA-F]{4}-[\\da-fA-F]{4}-[\\da-fA-F]{4}-[\\da-fA-F]{12}',
            },
            'parameters': ['organizationId'],
        },
        'profile.show': { 'uri': 'user/profile', 'methods': ['GET', 'HEAD'] },
        'other-browser-sessions.destroy': {
            'uri': 'user/other-browser-sessions',
            'methods': ['DELETE'],
        },
        'team-invitations.accept': {
            'uri': 'team-invitations/{invitation}',
            'methods': ['GET', 'HEAD'],
            'parameters': ['invitation'],
            'bindings': { 'invitation': 'id' },
        },
        'organization-invitations.accept': {
            'uri': 'organization-invitations/{invitation}',
            'methods': ['GET', 'HEAD'],
            'parameters': ['invitation'],
            'bindings': { 'invitation': 'id' },
        },
        'users.verify-email-change': {
            'uri': 'users/{user}/verify-email-change',
            'methods': ['GET', 'HEAD'],
            'parameters': ['user'],
            'bindings': { 'user': 'id' },
        },
        'telescope': {
            'uri': 'telescope/{view?}',
            'methods': ['GET', 'HEAD'],
            'wheres': { 'view': '(.*)' },
            'parameters': ['view'],
        },
        'storage.local': {
            'uri': 'storage/{path}',
            'methods': ['GET', 'HEAD'],
            'wheres': { 'path': '.*' },
            'parameters': ['path'],
        },
        'storage.local.upload': {
            'uri': 'storage/{path}',
            'methods': ['PUT'],
            'wheres': { 'path': '.*' },
            'parameters': ['path'],
        },
        'scramble.docs.ui': { 'uri': 'docs/api', 'methods': ['GET', 'HEAD'] },
        'scramble.docs.document': { 'uri': 'docs/api.json', 'methods': ['GET', 'HEAD'] },
    },
};
if (typeof window !== 'undefined' && typeof window.Ziggy !== 'undefined') {
    Object.assign(Ziggy.routes, window.Ziggy.routes);
}
export { Ziggy };
